package br.edu.ifba.inf008.plugins.usacase;

import br.edu.ifba.inf008.interfaces.IDatabaseService;
import br.edu.ifba.inf008.interfaces.models.User;
import br.edu.ifba.inf008.plugins.infrastructure.UserDAO;

import java.time.LocalDate;
import java.util.List;

public class UserService {
    private final UserDAO userDAO;

    public UserService(IDatabaseService databaseService) {
        this.userDAO = new UserDAO(databaseService);
    }

    public User createUser(String name, String email) {
        // Implement validation logic here if needed, e.g., check email format
        User newUser = new User(null, name, email, LocalDate.now()); // ID will be generated by DAO
        userDAO.save(newUser);
        return newUser;
    }

    public User updateUser(User user) {
        // Implement validation logic here
        userDAO.update(user);
        return user;
    }

    public boolean deleteUser(String id) {
        // Add checks for active loans if necessary
        userDAO.delete(id);
        return true; // Return false if deletion fails
    }

    public User getUserById(String id) {
        return userDAO.findById(id);
    }

    public List<User> getAllUsers() {
        return userDAO.findAll();
    }
}
